
variables:
  CI: 1
  
before_script:
  - docker --version
  - git --version
  - node -v
  - npm -v

stages:
  - prepare
  - build
  - image

.when-to-run: &when_to_run
  rules:
    - if: $CI_COMMIT_MESSAGE !~ /^\d+.\d+.\d+/
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+\S*$/

# prepare
job:prepare:
  stage: prepare

  script:
    - npm i  --no-audit --no-fund --verbose
  artifacts:
    expire_in: 15min
    paths:
      - node_modules/
  allow_failure: false
  <<: *when_to_run

# build: eslint
job:build:eslint:
  stage: build

  script:
    - npm run eslint
  allow_failure: false
  <<: *when_to_run

# build: build
job:build:build:
  stage: build

  artifacts:
    expire_in: 10min
    paths:
      - dist/
  script:
    - npm run build
  allow_failure: false
  <<: *when_to_run

# build: test
job:build:test:
  stage: build

  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  variables:
    NODE_ENV: test
  before_script:
    - cp -rf env/.env.example .env.test 
    - export $(cat .env.test | xargs)
  script:
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit: junit.xml
      # cobertura: coverage/cobertura-coverage.xml
  allow_failure: false
  <<: *when_to_run

